### Upload QnA File
POST http://localhost:5229/api/admin/qna/upload
Content-Type: multipart/form-data; boundary=boundary123

--boundary123
Content-Disposition: form-data; name="file"; filename="qna.csv"
Content-Type: application/vnd.openxmlformats-officedocument.wordprocessingml.document

< ./qna.csv
--boundary123--


### Get QnA
GET http://localhost:5229/api/admin/qna/download HTTP/1.1


### Delete QnA
DELETE http://localhost:5229/api/admin/qna/delete HTTP/1.1